# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [3]:
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [5]:
print("The diameter of {} is {} kilometers".format(planet,diameter))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [3]:
d['k1'][3]['tricky'][3]['target'][3]


'hello'

# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [7]:
five=zeros+5
five

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [8]:
zero = (2,5)
zeros=np.zeros(zero)
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 5. Create an array of all the even integers from 20 to 35

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
a=np.arange(0,9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [11]:
import pandas as pd


In [13]:
df = {'name':['ssj','jothi','satti'],'age':[70,15,21]}
pd.DataFrame(df)

name  age
0    ssj   70
1  jothi   15
2  satti   21

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [17]:
pd.date_range(start="19-01-2023",end="10-02-2023")

DatetimeIndex(['2023-01-19', '2023-01-20', '2023-01-21', '2023-01-22',
               '2023-01-23', '2023-01-24', '2023-01-25', '2023-01-26',
               '2023-01-27', '2023-01-28',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=257, freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [18]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [19]:
pd.DataFrame(lists,columns=['s.no','name','age'])

s.no name  age
0     1  aaa   22
1     2  bbb   25
2     3  ccc   24